
name: Docker Hub Registry

on:
  push:
    branches:
      - teste
    tags:
      - 'v*'
  workflow_dispatch:  # Execução manual

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  afere_variavel:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret
        env:
          MY_SECRET: ${{ secrets.TK_GITHUB_REGISTRY }}
        if: ${{ env.MY_SECRET == '' }}
        run: echo "MY_SECRET não existe"

      - name: Secret not found
        env:
          MY_SECRET: ${{ secrets.TK_GITHUB_REGISTRY }}
        if: ${{ env.MY_SECRET != '' }}
        run: echo "MY_SECRET existe"

      - name: Variable content
        env:
          VAR: ${{ vars.REGISTRY }}
        if: ${{ env.VAR != '' }}
        run: echo ${{ vars.VAR }}

      - name: Variable content
        if: ${{ env.VAR != '' }}
        run: echo ${{ vars.REGISTRY }}