
name: Docker Hub Registry

on:
  push:
    branches:
      - teste

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  afere_variavel:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret
        env:
          MY_SECRET: ${{ secrets.TK_GITHUB_REGISTRY }}
        if: ${{ env.MY_SECRET == '' }}
        run: echo "MY_SECRET não existe"

      - name: Secret not found
        env:
          MY_SECRET: ${{ secrets.TK_GITHUB_REGISTRY }}
        if: ${{ env.MY_SECRET != '' }}
        run: echo "MY_SECRET existe"

      - name: Variable content
#        env:
        run: echo ${{ vars.DOCKER_USR }}

      - name: Variable content
        if: ${{ vars.REGISTRY != '' }}
        run: echo ${{ vars.REGISTRY }}

      - name: Variable content
#        env:
        if: ${{ vars.DOCKER_PROJETO != '' }}
        run: echo ${{ vars.DOCKER_PROJETO }}