name: CI

on:
  push:
    branches:
      - teste
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  docker:
    uses: rodrigorootrj/pipelines-labs/.github/workflows/docker.yaml@main

    with:
      image_name: ${{ vars.REPO }}/${{ vars.DOCKER_PROJETO }}-teste/${{ github.sha }}
      dockerfile: Dockerfile
      registry: ${{ vars.REGISTRY }}
      REGISTRY_USERNAME: ${{ vars.DOCKER_USR }}
    secrets:
      REGISTRY_PASSWORD: ${{ secrets.TK_GITHUB_REGISTRY }}