name: CI

on:
  push:
    branches:
      - teste

jobs:

  docker:
    uses: rodrigorootrj/pipelines-labs/.github/workflows/docker.yaml@main

    with:
      image_name: ${{ vars.DOCKER_PROJETO }}
      dockerfile: Dockerfile
      registry: ghcr.io
      REGISTRY_USERNAME: ${{ vars.DOCKER_USR }}
    secrets:
      REGISTRY_PASSWORD: ${{ secrets.DOCKER_TK }}